src/Containers/App/test/App.test.js, src/Containers/Game/test/Game.test.js, src/mockData/mockData.js, src/utilities/test/API.test.js
This PR addresses issue #`7`.
* Add test structures for App
* Add test structures for API
* Add mock data to mockData
* Add __mocks__ to utilities folder
* Add folders and test folders for actions and reducers
* Verify that all the above files exist in pull request.
=> Iteration 0 ela

src/Components/Hint/Hint.scss, src/Components/Hint/index.js, src/Components/Results/Results.scss, src/Components/Results/index.js, src/Components/Results/test/__snapshots__/Results.test.js.snap, src/Containers/App/index.js, src/Containers/App/test/App.test.js, src/Containers/Game/index.js, src/Containers/Game/test/Game.test.js, src/Containers/Game/test/__snapshots__/Game.test.js.snap, src/Containers/Login/index.js, src/Containers/Login/test/Login.test.js, src/Containers/Login/test/__snapshots__/Login.test.js.snap, src/mockData/mockData.js
This PR addresses issue #`9`.
*Add testing for Game, App, and Login
=> Hint result init bruce

src/utilities/allCountries.js
This PR addresses issue #`15`.
* Test Travis CI 1
=> Change country name in array

src/reducers/test/userReducer.test.js, src/reducers/userReducer.js, src/utilities/__mocks__/API.js, src/utilities/allCountries.js, src/utilities/test/API.test.js
This PR addresses issue #`19`.
* Add completed preliminary Redux reducer tests.
* Verify that all Redux reducers to date have been tested.
=> Redux tests

src/Components/Hint/index.js, src/Components/Hint/test/__snapshots__/Hint.test.js.snap, src/Components/Results/index.js, src/Components/Results/test/__snapshots__/Results.test.js.snap, src/Containers/Game/index.js, src/Containers/Game/test/Game.test.js, src/Containers/Game/test/__snapshots__/Game.test.js.snap
This PR addresses issue #`22`.
*  Add conditional rendering logic for Results component
*  Add conditional rendering logic for Hint component
* Game's giveHint function needs a refactor. It crashes the app when invoked, saying that hint questions aren't defined.
=> Results display bruce

src/utilities/API.js, src/utilities/Fetch.js, src/utilities/test/API.test.js, src/utilities/test/Fetch.test.js
This PR addresses issue #`28`.
* Add passing tests for Fetch; fetchAllCountries and fetchCorrectCountry
* Move country fetch calls into separate file called Fetch.js
* Ensure that Fetch tests pass and that all previous functionality works as it did before.
=> Fetch api tests ela

package-lock.json, package.json, src/Components/Hint/Hint.scss, src/Components/Hint/index.js, src/Components/Hint/test/__snapshots__/Hint.test.js.snap, src/Containers/App/index.js, src/Containers/Game/index.js, src/Thunks/countries.js, src/Thunks/test/countries.test.js, src/actions/hasErroredAction.js, src/actions/test/hasErroredAction.test.js, src/index.js, src/reducers/hasErroredReducer.js, src/reducers/test/hasErroredReducer.test.js, src/utilities/Fetch.js, src/utilities/helper.js, src/utilities/test/Fetch.test.js, src/utilities/test/helper.test.js
This PR addresses issue #`21, 22, 28, 30`.
* Render country facts in Hint component upon 1st click of 'hint' button.
* Render country outline in Hint component upon 2nd click of 'hint' button.
* Add fetch call for country facts
* Add tests for country fact fetch calls
* Add property for `facts` for each country in Redux 
* Add tests for country facts property in buildQuestion function in helper.js
* Implement thunks for countries
* Test thunks for countries
* We still have a considerable number of tests to write in the Game component for the logic setting state for the Hints component.
* Verify that flags render upon page at random, and that clicking on 'hint' button correctly renders both country fact and outline hints.
=> Redux refactor thunk css ela

src/Components/Results/index.js, src/Components/Results/test/__snapshots__/Results.test.js.snap, src/Containers/Game/index.js, src/Containers/Game/test/Game.test.js, src/Containers/Game/test/__snapshots__/Game.test.js.snap, src/Containers/Login/Login.scss
This PR addresses issue #26, #24  .
* List the changes made
-Added a totalPoints value to state that changes on correct answer
-If the user guesses correct on the first try they add 3 points, 2 points after a hint, and 1 point after 2 hints
Please take a look and make sure you like the way i set it up, and that it won't interfere with anything further.
-I believe it should work when a new country populates the page but we won't know until we have that functionality
* List areas you would like reviewers to focus on
* Ex: The function beginning on line 72 is not pure; would love to have suggestions for improvement
* This is your opportunity to solicit particular attention for areas of code you are concerned about
-State on the …
=> Add points

.eslintrc, package.json, src/Components/Hint/index.js, src/Components/Hint/test/Hint.test.js, src/Components/Hint/test/__snapshots__/Hint.test.js.snap, src/Components/Results/test/Results.test.js, src/Components/Results/test/__snapshots__/Results.test.js.snap, src/index.js, src/utilities/test/helper.test.js
This PR addresses issue #`57, 58, 63`.
* Add passing tests for Results component.
* Add passing tests for Hint component.
* Converted Hint component into stateful one to assist with testing.
* Ran initial ESlint.
* While there are currently only 7 linting errors on my machine, some of the errors are unfamiliar to me.
Here is what I'm seeing:
```
/Users/alexanderela/Desktop/Personal Dropbox/Dropbox/_Turing_2018/Mod_4/Projects/cross_pollination_frontend/src/serviceWorker.js
30:1   warning  Line 30 exceeds the maximum line length of 80  max-len
38:1   warning  Line 38 exceeds the maximum line length of 80  max-len
44:11  error    Unexpected console statement                   no-console
63:30  error    Expected '===' and instead …
```
=> Eslint install

src/Containers/Game/index.js, src/Containers/Game/test/Game.test.js, src/Containers/Game/test/__snapshots__/Game.test.js.snap, src/Containers/Login/Login.scss
This PR addresses issue #56 .
-Tested all of Game component
-Made some changes to the addPoints function, if the answer is wrong, nothing changes so I don't think we need to setState there with no change to state. Also I simplified the variables. 
-import { wrap } from 'module';  No sure what this was in the test file. I removed it as I didn't see it performing anything.
* Confirm changes to addPoints function
=> Test game tobin

src/Containers/Account/Account.scss, src/Containers/Account/index.js, src/Containers/Account/test/__snapshots__/Account.test.js.snap, src/Containers/App/index.js, src/Containers/Game/Game.scss, src/Containers/Game/index.js, src/Containers/Game/test/__snapshots__/Game.test.js.snap, src/history.js, src/utilities/helper.js
This PR addresses issue #`77`.
* Create logic that avoids duplicate countries in creation of multiple choices
* Create logic that avoids a fifth option from being created if there are duplicates
* Update snapshots
* Force component re-rendering when changing routes between Game and Account
* Make flags visually more prominent
* Add functionality to keep all flags appropriate sizes, regardless of dimensions
* List areas you would like reviewers to focus on
* Ex: The function beginning on line 72 is not pure; would love to have suggestions for improvement
* This is your opportunity to solicit particular attention for areas of code you are concerned about
=> Accounts bruce

src/Containers/App/index.js, src/Containers/App/test/__snapshots__/App.test.js.snap, src/Containers/Game/index.js, src/Containers/Game/test/Game.test.js, src/Containers/Game/test/__snapshots__/Game.test.js.snap, src/Containers/Login/index.js, src/Containers/Login/test/Login.test.js, src/Containers/Login/test/__snapshots__/Login.test.js.snap, src/Thunks/test/users.test.js, src/Thunks/user.js, src/actions/test/userActions.test.js, src/actions/userActions.js, src/reducers/test/userReducer.test.js, src/reducers/userReducer.js, src/utilities/API.js, src/utilities/test/API.test.js
This PR addresses issue #`68, 68`.
* Removed '/login' router path.
* Added conditional rendering for '/' path that renders Game if user is logged in and Login if user is not logged in.
* Fixed failing tests in API, userActions, and userReducers.
* There is a skipped test in API.test.js that needs attention.
* The test in question is for getUser and reads 'should call fetch on path /api/signin'.
=> Login error ela

src/Containers/App/index.js, src/Containers/Game/index.js, src/Containers/Login/Login.scss, src/Containers/Login/index.js, src/reducers/index.js, src/reducers/loadingReducer.js, src/reducers/test/loadingReducer.test.js
This PR addresses issue #`<NUMBER>`.
Added user functionality as well as error handler for email and password
none
=> Add error for email

package-lock.json, package.json, src/Containers/Account/Account.scss, src/Containers/App/index.js, src/utilities/Fetch.js
This PR addresses issue #`77`.
* Add functionality to verify that country has not already been selected before fetching random country.
* Ensure that countries are not being repeated in Redux state.
=> Used countries duplicates ela

src/Containers/Login/index.js
added component will unmount lifecycle method to Login to get rid of memory leak error
let me know if you have any questions on what this does or why i did it 
None
=> Add component will unmount to fix error with memory leak

src/Containers/Account/index.js, src/Containers/App/index.js, src/Containers/App/test/App.test.js, src/Containers/Game/index.js, src/Containers/Game/test/__snapshots__/Game.test.js.snap
This PR addresses issue #`31`.
*Store points in local storage so they persist throughout a game
*Clear points on log out
*decrement hint counter
*cleaned out unused code on App
=> Point system

src/Containers/Game/Game.scss, src/Containers/Game/index.js, src/Containers/Game/test/__snapshots__/Game.test.js.snap, src/Containers/Login/Login.scss
This PR addresses issue #`21`.
* set Login's error element to position absolute so that it doesn't affect other elements
* Add hint logic that tells the user how many hints they have left in a round, or if they're out of hints, it tells them so and disables the button
*Update snapshot tests and clean up hint functionality
=> Hint button bruce

src/Components/Results/index.js, src/Components/Results/test/__snapshots__/Results.test.js.snap, src/Containers/Account/Account.scss, src/Containers/Account/index.js
This PR addresses issue #``.
* If user gets a guess wrong, Result popup will now say '0 pts'
* Add logic so that if the user gets one point it says '1 pt' instead of '1 pts'
* Add re-routing to logout button that the Login component displays instead of empty account page
=> Results handling bruce

package.json
Hides all the file paths in our coverage that don't need to be tested
=> Get rid of file path that dont need to be in coverage

src/Containers/Account/Account.scss, src/Containers/Game/index.js
This PR addresses issue #`102`.
* Check for country outline filepath error that we saw in eval, but found none
* Remove totalPoints proptype from Game
* Fix console warnings
* Ensure that back arrow in Account and country outline hints work properly
=> Remove totalPoints propType in Game, fix console warnings

src/Components/Hint/Hint.scss, src/Components/Results/Results.scss, src/Containers/Account/Account.scss, src/Containers/App/App.scss, src/Containers/Game/Game.scss, src/Containers/Login/Login.scss, src/Containers/Login/index.js
* Add styling to every component so that it should look clean and natural on any screen size
* I will add more desktop styling over time
* I think i made pretty much all of the CSS changes necessary to convert to desktop, but let me know if there are any other functionality related style changes that need to be made before a redesign
=> Desktop login styles ab
